#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

SERVICE=/usr/libexec/libernet-fan-daemon

start_service() {
	procd_open_instance
	procd_set_param command "$SERVICE"
	procd_set_param respawn 3600 5 5
	procd_close_instance
}
